In [15]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

import pandas as pd
from src.data_loader import load_data
from src.data_loader import load_query

## Load analytical views

In [16]:

customer_summary_df = load_data("customer_summary")
order_df = load_data("order_summary")
product_df = load_data("product_summary")
seller_df = load_data("seller_summary")
customers_df = load_data("customers")

## checking the successful loading of query using query_loader function

In [17]:

query = """
SELECT
    customer_state,
    COUNT(*) AS total_customers
FROM customers
GROUP BY customer_state
ORDER BY total_customers DESC
LIMIT 10;
"""

state_df = load_query(query)

In [18]:
state_df

  customer_state  total_customers
0             SP            41746
1             RJ            12852
2             MG            11635
3             RS             5466
4             PR             5045
5             SC             3637
6             BA             3380
7             DF             2140
8             ES             2033
9             GO             2020

## Verifying the successful loading of analytical views data

In [20]:
customer_summary_df.head()

,customer_unique_id,total_orders,total_spent,total_products,total_freight_paid,avg_order_value,avg_review_score,avg_delivery_days,first_purchase,last_purchase,customer_lifetime_days
0,0000366f3b9a7992bf8c76cfdf3221e2,1,141.90,1,12.00,141.90,5.00,6.00,2018-05-10,2018-05-10,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,27.19,1,8.29,27.19,4.00,3.00,2018-05-07,2018-05-07,0
2,0000f46a3911fa3c0805444483337064,1,86.22,1,17.22,86.22,3.00,26.00,2017-03-10,2017-03-10,0
3,0000f6ccb0745a6a4b88665a16c9f078,1,43.62,1,17.63,43.62,4.00,20.00,2017-10-12,2017-10-12,0
4,0004aac84e0df4da2b147fca70cf8255,1,196.89,1,16.89,196.89,5.00,13.00,2017-11-14,2017-11-14,0

In [21]:
product_df.head()

,product_id,product_category_name,total_units_sold,total_orders,total_revenue,total_freight,avg_price,avg_review_score,avg_delivery_days
0,00066f42aeeb9f3007548bb9d3f33c38,perfumaria,1,1,101.65,18.59,101.65,5.00,17.00
1,00088930e925c41fd95ebfe695fd2655,automotivo,1,1,129.90,13.93,129.90,4.00,11.00
2,0009406fd7479715e4bef61dd91f2462,cama_mesa_banho,1,1,229.00,13.10,229.00,1.00,16.00
3,000b8f95fcb9e0096488278317764d19,utilidades_domesticas,2,2,117.80,39.20,58.90,5.00,6.50
4,000d9be29b5207b54e86aa1b1ac54872,relogios_presentes,1,1,199.00,19.27,199.00,5.00,7.00

In [22]:
order_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay_days,total_items,distinct_sellers,total_product_price,total_freight,total_payment,product_payment,review_score
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,7.0,-9.0,1,1,58.90,13.29,72.19,58.90,5.00
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,16.0,-3.0,1,1,239.90,19.93,259.83,239.90,4.00
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,8.0,-14.0,1,1,199.00,17.87,216.87,199.00,5.00
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,6.0,-6.0,1,1,12.99,12.79,25.78,12.99,4.00
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,25.0,-16.0,1,1,199.90,18.14,218.04,199.90,5.00

In [23]:
seller_df.head()

,seller_id,seller_city,seller_state,total_orders,total_units_sold,total_revenue,total_freight,avg_product_price,avg_review_score,avg_delivery_days
0,0015a82c2db000af6aaaf3ae2ecb0532,santo andre,SP,3,3,2685.00,63.06,895.00,3.67,10.67
1,001cca7ae9ae17fb1caed9dfb1094831,cariacica,ES,200,239,25080.03,8854.14,104.94,3.90,13.11
2,001e6ad469a905060d959994f1b41e4f,sao goncalo,RJ,1,1,250.00,17.94,250.00,1.00,None
3,002100f778ceb8431b7a1020ff7ab48f,franca,SP,51,55,1234.50,793.66,22.45,3.98,16.00
4,003554e2dce176b5555353e4f3555ac8,goiania,GO,1,1,120.00,19.38,120.00,5.00,4.00

## Checking the dimensions

In [24]:
print(f"Customer_summary shape: {customer_df.shape}")
print(f"Order_summary shape: {order_df.shape}")
print(f"Product_summary Shape: {product_df.shape}")
print(f"Seller_summary Shape: {seller_df.shape}")

Customer_summary shape: (95420, 11)
Order_summary shape: (98666, 17)
Product_summary Shape: (32951, 9)
Seller_summary Shape: (3095, 10)