### Loding the data set

In [11]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

In [12]:
import pandas as pd
from src.data_loader import load_data
from src.data_loader import load_query

In [13]:
customer_df = load_data("customer_summary")
order_df = load_data("order_summary")
product_df = load_data("product_summary")
seller_df = load_data("seller_summary")

### Checking the dimensions

In [14]:
print(f"Customer_summary shape: {customer_df.shape}")
print(f"Order_summary shape: {order_df.shape}")
print(f"Product_summary Shape: {product_df.shape}")
print(f"Seller_summary Shape: {seller_df.shape}")

Customer_summary shape: (95420, 11)
Order_summary shape: (98666, 17)
Product_summary Shape: (32951, 9)
Seller_summary Shape: (3095, 10)

### Inspecting the column imfomations

#### Customers

In [15]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 95420 entries, 0 to 95419
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_unique_id      95420 non-null  str
 1   total_orders            95420 non-null  int64
 2   total_spent             95419 non-null  object
 3   total_products          95420 non-null  object
 4   total_freight_paid      95420 non-null  object
 5   avg_order_value         95419 non-null  object
 6   avg_review_score        94721 non-null  object
 7   avg_delivery_days       93356 non-null  object
 8   first_purchase          95420 non-null  object
 9   last_purchase           95420 non-null  object
 10  customer_lifetime_days  95420 non-null  int64
dtypes: int64(2), object(8), str(1)
memory usage: 8.0+ MB

It is found that several numerical columns returned the data type as objects, so it is necessary to convert them into numeric value for the further analysis

#### For Orders

In [16]:
order_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 98666 entries, 0 to 98665
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       98666 non-null  str
 1   customer_id                    98666 non-null  str
 2   order_status                   98666 non-null  str
 3   order_purchase_timestamp       98666 non-null  datetime64[us]
 4   order_approved_at              98652 non-null  datetime64[us]
 5   order_delivered_carrier_date   97657 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  98666 non-null  datetime64[us]
 8   delivery_days                  96476 non-null  float64
 9   delivery_delay_days            96476 non-null  float64
 10  total_items                    98666 non-null  int64
 11  distinct_sellers               98666 non-null  int64
 12  total_product_price            98666 non-null  object
 13  total_freight                  98666 non-null  object
 14  total_payment                  98665 non-null  object
 15  product_payment                98665 non-null  object
 16  review_score                   97917 non-null  object
dtypes: datetime64[us](5), float64(2), int64(2), object(5), str(3)
memory usage: 12.8+ MB

It is found that several numerical columns returned the data type as objects, so it is necessary to convert them into numeric value for the further analysis

#### For Products

In [17]:
product_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             32951 non-null  str
 1   product_category_name  32341 non-null  str
 2   total_units_sold       32951 non-null  int64
 3   total_orders           32951 non-null  int64
 4   total_revenue          32951 non-null  object
 5   total_freight          32951 non-null  object
 6   avg_price              32951 non-null  object
 7   avg_review_score       32789 non-null  object
 8   avg_delivery_days      32214 non-null  object
dtypes: int64(2), object(5), str(2)
memory usage: 2.3+ MB

It is found that several numerical columns returned the data type as objects, so it is necessary to convert them into numeric value for the further analysis

#### For Sellers

In [18]:
seller_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   seller_id          3095 non-null   str
 1   seller_city        3095 non-null   str
 2   seller_state       3095 non-null   str
 3   total_orders       3095 non-null   int64
 4   total_units_sold   3095 non-null   int64
 5   total_revenue      3095 non-null   object
 6   total_freight      3095 non-null   object
 7   avg_product_price  3095 non-null   object
 8   avg_review_score   3090 non-null   object
 9   avg_delivery_days  2970 non-null   object
dtypes: int64(2), object(5), str(3)
memory usage: 241.9+ KB

It is found that several numerical columns returned the data type as objects, so it is necessary to convert them into numeric value for the further analysis

### Analyse the Descriptive Statistics

In [19]:
customer_df.describe()

       total_orders  customer_lifetime_days
count  95420.000000            95420.000000
mean       1.034018                2.683389
std        0.211234               25.263074
min        1.000000                0.000000
25%        1.000000                0.000000
50%        1.000000                0.000000
75%        1.000000                0.000000
max       16.000000              633.000000

In [20]:
order_df.describe()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay_days,total_items,distinct_sellers
count,98666,98652,97657,96476,98666,96476.000000,96476.000000,98666.000000,98666.000000
mean,2017-12-31 22:05:22.366559,2018-01-01 09:30:11.667913,2018-01-04 21:56:02.570537,2018-01-14 12:09:19.035542,2018-01-24 16:36:25.409360,12.497336,-11.876881,1.141731,1.013622
min,2016-09-04 21:15:19,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-10-04 00:00:00,0.000000,-147.000000,1.000000,1.000000
25%,2017-09-12 23:21:27.500000,2017-09-13 15:37:19.500000,2017-09-15 22:31:51,2017-09-25 22:07:22.250000,2017-10-04 00:00:00,7.000000,-17.000000,1.000000,1.000000
50%,2018-01-19 18:02:47,2018-01-20 09:10:39,2018-01-24 16:12:38,2018-02-02 19:28:10.500000,2018-02-15 00:00:00,10.000000,-12.000000,1.000000,1.000000
75%,2018-05-04 20:05:35.250000,2018-05-05 07:16:04,2018-05-08 13:38:00,2018-05-15 22:48:52.250000,2018-05-28 00:00:00,16.000000,-7.000000,1.000000,1.000000
max,2018-09-03 09:06:57,2018-09-03 17:40:06,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-10-25 00:00:00,210.000000,188.000000,21.000000,5.000000
std,NaN,NaN,NaN,NaN,NaN,9.555460,10.183854,0.538452,0.122297

### Check Missing values

In [21]:
customer_df.isnull().sum()

customer_unique_id           0
total_orders                 0
total_spent                  1
total_products               0
total_freight_paid           0
avg_order_value              1
avg_review_score           699
avg_delivery_days         2064
first_purchase               0
last_purchase                0
customer_lifetime_days       0
dtype: int64

In [22]:
order_df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  14
order_delivered_carrier_date     1009
order_delivered_customer_date    2190
order_estimated_delivery_date       0
delivery_days                    2190
delivery_delay_days              2190
total_items                         0
distinct_sellers                    0
total_product_price                 0
total_freight                       0
total_payment                       1
product_payment                     1
review_score                      749
dtype: int64

In [23]:
product_df.isnull().sum()

product_id                 0
product_category_name    610
total_units_sold           0
total_orders               0
total_revenue              0
total_freight              0
avg_price                  0
avg_review_score         162
avg_delivery_days        737
dtype: int64

In [24]:
seller_df.isnull().sum()

seller_id              0
seller_city            0
seller_state           0
total_orders           0
total_units_sold       0
total_revenue          0
total_freight          0
avg_product_price      0
avg_review_score       5
avg_delivery_days    125
dtype: int64

### Check duplicate values

In [25]:
customer_df.duplicated().sum()

np.int64(0)

In [26]:
order_df.duplicated().sum()

np.int64(0)

In [27]:
product_df.duplicated().sum()

np.int64(0)

In [28]:
seller_df.duplicated().sum()

np.int64(0)

### Verifying the date columns

In [30]:
print(order_df["order_purchase_timestamp"].min())
print(order_df["order_purchase_timestamp"].max())

2016-09-04 21:15:19
2018-09-03 09:06:57

### Verifying the categorical columns

In [31]:
order_df["order_status"].value_counts()

order_status
delivered      96478
shipped         1106
canceled         461
invoiced         312
processing       301
unavailable        6
approved           2
Name: count, dtype: int64

In [32]:
seller_df["seller_state"].value_counts()

seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
MA       1
AM       1
PI       1
AC       1
PA       1
Name: count, dtype: int64

All analytical views were successfully loaded from PostgreSQL. Dataset dimensions matched the SQL outputs, no duplicate records were detected, missing values were limited to expected fields, and numerical statistics fell within expected ranges. Therefore, the datasets are considered suitable for feature engineering and machine learning.